version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: live_weather_development
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  webpacker:
    image: 'web1'
    build:
      context: .
    ports:
      - 3035:3035
  web:
    image: 'web1'
    build:
      context: .
      args:
        precompileassets: "not"
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
      - webpacker
volumes:
  postgres:
